// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-1lizDbrShWixQWAnmkzrBVnahtVVK_g',
    appId: '1:717360332394:web:7da294b7739b20aee85413',
    messagingSenderId: '717360332394',
    projectId: 'gr05-easymed-fall-2025',
    authDomain: 'gr05-easymed-fall-2025.firebaseapp.com',
    storageBucket: 'gr05-easymed-fall-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAagiGW1sIZsbxA6J1xWrxVZvr19wGIp8',
    appId: '1:717360332394:android:824cacd1ea4ee524e85413',
    messagingSenderId: '717360332394',
    projectId: 'gr05-easymed-fall-2025',
    storageBucket: 'gr05-easymed-fall-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6dkOAiMGiMVM-wnfYLTf_l45mJ60ui5g',
    appId: '1:717360332394:ios:5efe81a81ac5b187e85413',
    messagingSenderId: '717360332394',
    projectId: 'gr05-easymed-fall-2025',
    storageBucket: 'gr05-easymed-fall-2025.firebasestorage.app',
    androidClientId: '717360332394-34o4la6qd8sm3emfkre0uimt2l07u3uq.apps.googleusercontent.com',
    iosClientId: '717360332394-dau5nfefd4epfnlkv9c5i8h5148ja9s7.apps.googleusercontent.com',
    iosBundleId: 'com.example.easymed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6dkOAiMGiMVM-wnfYLTf_l45mJ60ui5g',
    appId: '1:717360332394:ios:5efe81a81ac5b187e85413',
    messagingSenderId: '717360332394',
    projectId: 'gr05-easymed-fall-2025',
    storageBucket: 'gr05-easymed-fall-2025.firebasestorage.app',
    androidClientId: '717360332394-34o4la6qd8sm3emfkre0uimt2l07u3uq.apps.googleusercontent.com',
    iosClientId: '717360332394-dau5nfefd4epfnlkv9c5i8h5148ja9s7.apps.googleusercontent.com',
    iosBundleId: 'com.example.easymed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-1lizDbrShWixQWAnmkzrBVnahtVVK_g',
    appId: '1:717360332394:web:547e25ed434a2beae85413',
    messagingSenderId: '717360332394',
    projectId: 'gr05-easymed-fall-2025',
    authDomain: 'gr05-easymed-fall-2025.firebaseapp.com',
    storageBucket: 'gr05-easymed-fall-2025.firebasestorage.app',
  );
}
